### PR TITLE
Update CI configs to v0.1.0

### PR DESCRIPTION
**Pull request by pionbot**
Update lint scripts and CI configs.

### CODE REVIEW

**Comment by at-wat** [comment]
```
$ bash .github/lint-disallowed-functions-in-library.sh
/home/travis/gopath/src/github.com/pion/turn/.github/../internal/proto/fuzz.go:		panic(err)
/home/travis/gopath/src/github.com/pion/turn/.github/../internal/proto/fuzz.go:		panic(err)
/home/travis/gopath/src/github.com/pion/turn/.github/../internal/proto/fuzz.go:		panic(err)
/home/travis/gopath/src/github.com/pion/turn/.github/../internal/proto/fuzz.go:		panic("not equal")
/home/travis/gopath/src/github.com/pion/turn/.github/../internal/proto/fuzz.go:		panic(err)
panic( may only be used in example code
The command "bash .github/lint-disallowed-functions-in-library.sh" exited with 1.
```

**Comment by at-wat** [comment]
```
# github.com/pion/turn/v2
./client.go:418: Errorf format %w has unknown verb w
./server.go:95: Errorf format %w has unknown verb w
```
Go 1.13 error wrapping is used. Build on Go 1.12 fails.
